'use strict';
const CONFIG=window.WORKOUT_CONFIG,KEY='workout-history-v1',week=['日','一','二','三','四','五','六'];
const groups=Object.fromEntries(Object.values(CONFIG.days).flatMap(d=>d.groups).map(g=>[g.id,g]));
const targets={};for(const n of CONFIG.trainingDays)for(const g of CONFIG.days[n].groups)targets[g.id]=(targets[g.id]||0)+1;
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function today(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function dow(d){return new Date(d+'T12:00:00Z').getUTCDay()}
function add(d,n){return new Date(Date.parse(d+'T12:00:00Z')+n*86400000).toISOString().slice(0,10)}
function monday(d){return add(d,-((dow(d)+6)%7))}
let stamp=today(),view='daily',notice='',storageOK=true,state={days:{}};
try{const s=JSON.parse(localStorage.getItem(KEY));if(s?.days&&typeof s.days==='object')state=s}catch{storageOK=false}
function prune(){for(const date of Object.keys(state.days)){if(date<add(stamp,-13)||date>stamp){delete state.days[date];continue}const d=state.days[date];if(!Array.isArray(d.items)){delete state.days[date];continue}if(date!==stamp)d.active=null;d.items=d.items.filter(x=>x&&typeof x.gid==='string');if(date===stamp)d.items=d.items.filter(x=>groups[x.gid]&&groups[x.gid].options.some(o=>o.id===x.choice));}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch{storageOK=false}}
function item(g){return {gid:g.id,choice:g.options[0].id,done:false,started:false,title:g.title,muscles:g.muscles,reason:''}}
function session(){if(!state.days[stamp]){const n=dow(stamp),base=CONFIG.trainingDays.includes(n)?CONFIG.days[n].groups:[];state.days[stamp]={active:null,mode:base.length?'training':n===1?'badminton':'rest',items:base.map(item)}}return state.days[stamp]}
function records(){return Object.entries(state.days).flatMap(([date,d])=>d.items.filter(i=>i.done).map(i=>({...i,date})))}
function counts(date=stamp){const out={};for(const r of records())if(r.date>=monday(date)&&r.date<=date)out[r.gid]=(out[r.gid]||0)+1;return out}
// A deterministic prioritization rule, not a physiological recovery estimate.
function recommend(date=stamp,locked=[]){const count=counts(date),used=new Set(locked.map(i=>i.gid));const base=new Set(CONFIG.days[dow(date)].groups.map(g=>g.id));const recent=records().filter(r=>r.date>=add(date,-2)&&r.date<=date);const picks=[];
 for(let slot=locked.length;slot<3;slot++){
 const candidates=Object.values(groups).filter(g=>!used.has(g.id)&&(targets[g.id]||0)>(count[g.id]||0));
 const ranked=candidates.map(g=>{const overlap=recent.some(r=>(r.muscles||[]).some(m=>g.muscles.includes(m)));const same=recent.some(r=>r.gid===g.id);const clustered=picks.some(p=>p.muscles.some(m=>g.muscles.includes(m)));return {g,overlap,score:(base.has(g.id)?15:0)- (overlap?30:0)-(same?20:0)-(clustered?5:0)}}).sort((a,b)=>b.score-a.score||a.g.id.localeCompare(b.g.id));
 if(!ranked.length)break;const {g,overlap}=ranked[0],it=item(g);it.reason=`本週 ${count[g.id]||0}／${targets[g.id]} 次${base.has(g.id)?'，原定今日群組':''}${overlap?'；近兩天有重疊部位，請依恢復調整':'，近期無已記錄的部位重疊'}`;picks.push(it);used.add(g.id);
 }return picks;
}
function locked(i,d){return i.done||i.started||d.active===d.items.indexOf(i)}
function applyRecommendation(){const d=session(),keep=d.items.filter(i=>locked(i,d)),active=d.active===null?null:d.items[d.active];const next=recommend(stamp,keep);d.items=[...keep,...next];d.active=active?d.items.indexOf(active):null;d.mode='training';notice=next.length?'已更新尚未開始的項目。':'本週群組目標已完成；可休息，或自行選擇課表。';save()}
function chooseTemplate(n){const d=session();if(d.items.some(i=>locked(i,d))){notice='已有開始或完成的項目；請先停止目前項目並取消完成，再更換整套課表。';return}d.items=CONFIG.days[n].groups.map(item);d.mode='training';d.active=null;notice='已套用課表，完成紀錄會記在今天 '+stamp+'。';save()}
function toggleDone(i){const d=session(),x=d.items[i];x.done=!x.done;if(x.done){const g=groups[x.gid],o=g.options.find(o=>o.id===x.choice);x.title=g.title;x.name=o.cn;x.en=o.en;x.muscles=[...g.muscles];x.completedAt=new Date().toISOString()}else{x.started=false;delete x.completedAt}if(d.active===i)d.active=null;save()}
function rollover(){const now=today();if(now===stamp)return false;stamp=now;notice='已切換至今天；過去完成紀錄保留 14 天。';prune();session();save();render();return true}
function reps(g,id){return g.options.find(o=>o.id===id)?.reps||g.reps}
function options(g){return `<ul>${g.options.map(o=>`<li>${esc(o.cn)}<span class="english">${esc(o.en)}</span><span class="reps">${esc(reps(g,o.id))}</span></li>`).join('')}</ul>`}
function renderWeek(){const start=monday(stamp),c=counts();document.getElementById('weekly').innerHTML=`<h2>本週計畫</h2><p class="muted">以週三至週六為基準。未來推薦根據目前已完成紀錄計算，不預先假設你會完成其他天。</p><details><summary>本週群組完成量</summary>${Object.entries(targets).map(([id,n])=>`<p>${esc(groups[id].title)}：${c[id]||0}／${n} 次（每次完整一項）</p>`).join('')}</details>`+Array.from({length:7},(_,i)=>{const date=add(start,i),n=dow(date),base=CONFIG.days[n],actual=state.days[date]?.items.filter(i=>i.done)||[],suggested=date>=stamp&&CONFIG.trainingDays.includes(n)?recommend(date):[];return `<article class="week-card ${date===stamp?'today':''}"><div class="week-head"><h3>週${week[n]} · ${n===1?'羽球／補充重訓':esc(base.title)}</h3><span class="badge">${date===stamp?'今天':date.slice(5)}</span></div><p class="muted">原定：${base.groups.length?base.groups.map(g=>esc(g.title)).join('、'):'休息'}</p>${actual.length?`<p>已完成：${actual.map(i=>esc(i.title)).join('、')}</p>`:''}${suggested.length?`<p>目前推薦：${suggested.map(i=>esc(groups[i.gid].title)).join('、')}</p><details><summary>推薦原因</summary>${suggested.map(i=>`<p>${esc(groups[i.gid].title)}：${esc(i.reason)}</p>`).join('')}</details>`:''}${base.groups.length?`<details><summary>原課表器材與組次</summary>${base.groups.map(g=>`<h4>${esc(g.title)}</h4>${options(g)}`).join('')}</details><button class="start" data-template="${n}">今天改練這套</button>`:''}</article>`}).join('');}
function renderHistory(){return `<details><summary>最近 14 天完成紀錄（可撤回）</summary>${Object.entries(state.days).sort(([a],[b])=>b.localeCompare(a)).map(([date,d])=>d.items.map((x,i)=>x.done?`<div class="history-row">${date} · ${esc(x.title)}<br>${esc(x.name||'')}<span class="english">${esc(x.en||'')}</span><button class="start" data-undo="${date}:${i}">撤回這筆完成</button></div>`:'').join('')).join('')||'<p class="muted">尚無完成紀錄。</p>'}</details>`}
function render(){const d=session();document.getElementById('date').textContent=stamp+' · 週'+week[dow(stamp)];document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===view)));document.getElementById('weekly').hidden=view!=='weekly';for(const id of ['days','mode','workout'])document.getElementById(id).hidden=view==='weekly';document.getElementById('warning').textContent=storageOK?notice:'瀏覽器無法保存；關閉後可能遺失。 '+notice;if(view==='weekly'){renderWeek();return}
 document.getElementById('days').innerHTML='<p class="muted">完成動作一律記錄在今天，課表可自由更換。</p>';
 document.getElementById('mode').innerHTML=`<label>今天想練哪一套？<select id="template"><option value="">選擇課表…</option>${[3,4,5,6,1].map(n=>`<option value="${n}">${esc(CONFIG.days[n].title)}${n===1?'（補充）':''}</option>`).join('')}</select></label><div class="toolbar"><button class="start" data-recommend>更新推薦</button><button class="start" data-mode="rest">今天休息</button>${dow(stamp)===1?'<button class="start" data-mode="badminton">今天打羽球</button>':''}</div>`;
 const done=d.items.filter(i=>i.done).length;
 document.getElementById('workout').innerHTML=d.mode!=='training'?`<div class="rest"><h2>${d.mode==='badminton'?'今天打羽球':'今天休息'}</h2><p>也可以從上方選擇課表，安排今天的重訓。</p></div>${renderHistory()}`:`<div class="summary"><h2>今天的安排</h2><div class="count">${done}<span> / ${d.items.length} 項完成</span></div></div><p class="muted">最多三項；完成一項代表完成該動作的全部正式組。</p><div class="cards">${d.items.map((x,i)=>{const g=groups[x.gid],fixed=locked(x,d);return `<article class="card ${d.active===i?'active':''} ${x.done?'done':''}"><div class="card-head"><div class="topline">項目 ${i+1}<span class="badge">${x.done?'已完成':d.active===i?'進行中':x.started?'已開始':'未開始'}</span></div><label>訓練群組<select data-group="${i}" ${fixed?'disabled':''}>${Object.values(groups).map(a=>`<option value="${a.id}" ${a.id===g.id?'selected':''}>${esc(a.title)}</option>`).join('')}</select></label><p class="reps">${esc(reps(g,x.choice))}</p>${x.reason?`<p class="reason">${esc(x.reason)}</p>`:''}</div><fieldset class="options" ${fixed?'disabled':''}><legend>今天使用的器材</legend>${g.options.map(o=>`<label class="option"><input type="radio" name="choice-${i}" data-choice="${i}" value="${o.id}" ${x.choice===o.id?'checked':''}><span><strong>${esc(o.cn)}</strong><span class="english">${esc(o.en)}</span></span></label>`).join('')}</fieldset><div class="actions"><button class="start" data-start="${i}" ${x.done?'disabled':''}>${x.started?'停止／解除鎖定':'開始此項'}</button><label class="complete"><input type="checkbox" data-done="${i}" ${x.done?'checked':''}>${x.done?'取消完成':'標記完成'}</label></div></article>`}).join('')}</div>${!d.items.length?'<p>本週目標已完成，可休息或自行選擇課表。</p>':''}<div class="walk"><span>訓練後 · Walking</span><strong>${esc(CONFIG.walking)}</strong></div>${renderHistory()}`;
}
document.addEventListener('click',e=>{if(rollover())return;const b=e.target.closest('button');if(!b)return;const d=session();if(b.dataset.view){view=b.dataset.view}else if(b.hasAttribute('data-recommend'))applyRecommendation();else if(b.dataset.template){chooseTemplate(Number(b.dataset.template));view='daily'}else if(b.dataset.mode){d.mode=b.dataset.mode;d.active=null;save()}else if(b.dataset.start!==undefined){const i=Number(b.dataset.start),x=d.items[i];if(!x.done){x.started=!x.started;d.active=x.started?i:null;save()}}else if(b.dataset.undo){const [date,idx]=b.dataset.undo.split(':');const x=state.days[date]?.items[Number(idx)];if(x){x.done=false;x.started=false;delete x.completedAt;save()}}else return;render()});
document.addEventListener('change',e=>{if(rollover())return;const d=session(),t=e.target;if(t.id==='template'&&t.value)chooseTemplate(Number(t.value));else if(t.dataset.group!==undefined){const i=Number(t.dataset.group);if(!locked(d.items[i],d)){if(d.items.some((x,j)=>j!==i&&x.gid===t.value)){notice='今天已有這個群組，請選不同項目。'}else d.items[i]=item(groups[t.value]);save()}}else if(t.dataset.choice!==undefined){const x=d.items[Number(t.dataset.choice)];if(!locked(x,d)){x.choice=Number(t.value);save()}}else if(t.dataset.done!==undefined)toggleDone(Number(t.dataset.done));else return;render()});
setInterval(rollover,1000);window.addEventListener('focus',rollover);document.addEventListener('visibilitychange',()=>{if(!document.hidden)rollover()});window.addEventListener('storage',e=>{if(e.key===KEY){try{state=JSON.parse(localStorage.getItem(KEY))||{days:{}};prune();render()}catch{}}});
prune();session();save();render();
