'use strict';
const CONFIG=window.WORKOUT_CONFIG, KEY='workout-history-v1';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function today(){return new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Taipei',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function add(d,n){return new Date(Date.parse(d+'T12:00:00Z')+n*86400000).toISOString().slice(0,10)}
function monday(d){return add(d,-((new Date(d+'T12:00:00Z').getUTCDay()+6)%7))}
const list=CONFIG.weeklyGroups;
let selectedCombo='all';
let stamp=today(),state={days:{},choices:{}},storageOK=true;
try{const saved=JSON.parse(localStorage.getItem(KEY));if(saved?.days&&typeof saved.days==='object')state=saved}catch{storageOK=false}
state.choices=state.choices||{};
function prune(){for(const date of Object.keys(state.days))if(date<add(stamp,-13)||date>stamp||!Array.isArray(state.days[date]?.items))delete state.days[date];if(state.choiceWeek!==monday(stamp)){state.choices={};state.choiceWeek=monday(stamp)}}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch{storageOK=false}}
function records(){return Object.entries(state.days).flatMap(([date,d])=>d.items.map((item,index)=>({date,index,...item})).filter(r=>r.done))}
function completed(gid){return records().filter(r=>r.date>=monday(stamp)&&r.gid===gid)}
function complete(gid){const g=list.find(g=>g.id===gid);if(!g||completed(gid).length)return;const choice=Number(state.choices[gid]||g.options[0].id),o=g.options.find(o=>o.id===choice);if(!o)return;state.days[stamp]??={items:[]};state.days[stamp].items.push({gid:g.id,choice:o.id,done:true,title:g.title,name:o.cn,en:o.en,completedAt:new Date().toISOString()});save()}
function undo(gid){for(const [date,d] of Object.entries(state.days))if(date>=monday(stamp))for(const i of d.items)if(i.gid===gid)i.done=false;save()}
function reps(g,id){return g.options.find(o=>o.id===id)?.reps||g.reps}
function render(){const combo=(CONFIG.combinations||[]).find(c=>c.id===selectedCombo);const visible=combo?combo.groups.map(id=>list.find(g=>g.id===id)).filter(Boolean):list;const start=monday(stamp),count=list.filter(g=>completed(g.id).length).length;
 document.getElementById('date').textContent=stamp+' · 台灣';document.getElementById('warning').textContent=storageOK?'':'瀏覽器無法保存；關閉頁面後可能遺失紀錄。';
 document.getElementById('workout').innerHTML=`<div class="summary"><div><p class="muted">${start} — ${add(start,6)}</p><h2>本週完成</h2></div><div class="count">${count}<span> / ${list.length} 項</span></div></div><progress value="${count}" max="${list.length}" aria-label="本週完成 ${count} 項，共 ${list.length} 項"></progress><p class="muted">想練哪項就選哪項。完成所有正式組後，再勾選完成。</p><section class="combos" aria-label="建議搭配"><h2>建議搭配</h2><p class="muted">不綁定星期，可選一組查看，也可跨組挑動作。</p><button type="button" class="combo-all" data-combo="all" aria-pressed="${!combo}">全部項目 · ${list.length} 項</button><div class="combo-grid">${(CONFIG.combinations||[]).map(c=>`<button type="button" class="combo-button" data-combo="${esc(c.id)}" aria-pressed="${selectedCombo===c.id}"><strong>${esc(c.id)}｜${esc(c.title)}</strong><span>${c.groups.map(id=>esc(list.find(g=>g.id===id)?.title||id)).join('＋')}</span><span class="combo-progress">已完成 ${c.groups.filter(id=>completed(id).length).length}／${c.groups.length} 項</span></button>`).join('')}</div></section><h2 class="list-title">${combo?esc(combo.title):'全部訓練項目'}</h2><div class="cards">${visible.map((g,i)=>{const done=completed(g.id),record=done[0],choice=record?.choice||state.choices[g.id]||g.options[0].id;return `<article class="card ${record?'done':''}"><div class="card-head"><div class="topline">${String(i+1).padStart(2,'0')}<span class="badge">${record?'✓ '+record.date:'待完成'}</span></div><h3>${esc(g.title)}</h3><p class="reps">${esc(reps(g,choice))}</p><label>器材／動作<select data-choice="${g.id}" ${record?'disabled':''}>${g.options.map(o=>`<option value="${o.id}" ${Number(choice)===o.id?'selected':''}>${esc(o.cn)} · ${esc(o.en)}</option>`).join('')}</select></label>${record?`<span class="english">${esc(record.en||record.name||'')}</span>`:''}</div><div class="actions"><label class="complete"><input type="checkbox" data-done="${g.id}" ${record?'checked':''}>${record?'取消完成':'標記完成'}</label></div></article>`}).join('')}</div><section style="margin-top:28px"><details><summary>最近 14 天紀錄</summary>${records().sort((a,b)=>b.date.localeCompare(a.date)).map(r=>`<div class="history-row"><strong>${r.date} · ${esc(r.title)}</strong><br>${esc(r.name||'')}<span class="english">${esc(r.en||'')}</span><button class="start" data-undo="${r.date}:${r.index}">取消這筆紀錄</button></div>`).join('')||'<p class="muted">尚無完成紀錄。</p>'}</details></section>`;
}
function rollover(){const now=today();if(now===stamp)return false;stamp=now;prune();save();render();return true}
document.addEventListener('change',e=>{if(rollover())return;const t=e.target;if(t.dataset.choice){state.choices[t.dataset.choice]=Number(t.value);save()}else if(t.dataset.done){if(t.checked)complete(t.dataset.done);else undo(t.dataset.done)}else return;render()});
document.addEventListener('click',e=>{if(rollover())return;const filter=e.target.closest('[data-combo]');if(filter){selectedCombo=filter.dataset.combo;render();document.querySelector(`[data-combo="${selectedCombo}"]`)?.focus({preventScroll:true});return}const b=e.target.closest('[data-undo]');if(!b)return;const [date,index]=b.dataset.undo.split(':');const item=state.days[date]?.items[Number(index)];if(item){item.done=false;save();render()}});
setInterval(rollover,1000);window.addEventListener('focus',rollover);document.addEventListener('visibilitychange',()=>{if(!document.hidden)rollover()});window.addEventListener('storage',e=>{if(e.key===KEY){try{state=JSON.parse(localStorage.getItem(KEY))||{days:{},choices:{}};state.choices??={};prune();render()}catch{}}});
prune();save();render();
